import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import HomeHero from '@/components/HomeHero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>WUP - Potencialização Empresarial e Executiva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <HomeHero />
        <h1>Hello World</h1>
      </main>
    </>
  )
}
