import Head from 'next/head';
import Header from '@/components/Header';
import HomeHero from '@/components/HomeHero';
import SectionTwo from '@/components/SectionTwo';
import SectionThree from '@/components/SectionThree';
import SectionFour from '@/components/SectionFour';
import About from '@/components/About';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>WUP - Potencialização Empresarial e Executiva</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <HomeHero />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
        <About />
      </main>
      <Footer />
    </>
  )
}
